name: Build Android APK

on:
  push:
    branches: [ android, main, master ]
  pull_request:
    branches: [ android, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: List files
      run: ls -la
    
    - name: Install dependencies
      run: |
        cd rent-management-mobile
        npm install
    
    - name: Add Android platform
      run: |
        cd rent-management-mobile
        cordova platform add android
        cordova platform list
    
    - name: Verify configuration
      run: |
        cd rent-management-mobile
        echo "Checking config.xml for targetSdkVersion..."
        grep -n "android-targetSdkVersion" config.xml || echo "targetSdkVersion not found"
        echo "Checking if WhitelistPlugin.java exists..."
        if [ -f "platforms/android/app/src/main/java/org/apache/cordova/whitelist/WhitelistPlugin.java" ]; then
          echo "WhitelistPlugin.java found"
        else
          echo "WhitelistPlugin.java not found - this may cause build issues"
        fi
        echo "Configuration verified"
    
    - name: Build APK
      run: |
        cd rent-management-mobile
        echo "Starting Android build..."
        cordova build android --release
        echo "Build completed, looking for APK files..."
        find . -name "*.apk" -type f
        echo "APK search completed"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rent-management-apk
        path: rent-management-mobile/platforms/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: warn
