name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install -g cordova
        npm install
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Add Android platform
      run: |
        cd rent-management-mobile
        cordova platform add android
    
    - name: Build APK
      run: |
        cd rent-management-mobile
        cordova build android --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: rent-management-apk
        path: rent-management-mobile/platforms/android/app/build/outputs/apk/release/app-release.apk
