name: Build Android APK

on:
  push:
    branches: [ android, main, master ]
  pull_request:
    branches: [ android, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: List files
      run: ls -la
    
    - name: Add Android platform
      run: |
        cordova platform add android
        cordova platform list
    
    - name: Build APK
      run: |
        cordova build android --release
        find . -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rent-management-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: warn
